import math

WIDTH = 1200
HEIGHT = 800

HALF_WIDTH =  WIDTH // 2
HALF_HEIGHT = HEIGHT // 2

FPS = 60
TILE = 100

#MATEMATIKA

FOV = math.pi/3

HALF_FOV = FOV / 2
NUM_OF_RAYS = 100
MAX_DEPTH = 800

DELTA_ANGLE = FOV/NUM_OF_RAYS
DIST = NUM_OF_RAYS / (2 * math.tan(HALF_FOV))
PROJ_COEF = 3 * DIST * TILE

SCALE = WIDTH // NUM_OF_RAYS
SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)

#HRU HRU GRAVEC KOROLIVSKIY KABANCHIK

player_pos = [HALF_WIDTH, HALF_HEIGHT]
player_angle = 0
player_speed = 10

#COLYORI

WHITE = (255,255,255)
GREEN = (0,255,0)
RED = (255,0,0)
BLUE = (0,0,255)
YELLOW = (255,255,0)


TEXTURE_WIDHT = 500
TEXTURE_HEight = 500
TEXTTURE_SCALE = TEXTURE_WIDHT//TILE